# Generated by Django 5.2.4 on 2025-07-21 00:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_shelf_warehouse_remove_product_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex renk kodu (örn: #3B82F6)', max_length=7, verbose_name='Renk Kodu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gider Kategorisi',
                'verbose_name_plural': 'Gider Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Gider Başlığı')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Gider Tarihi')),
                ('payment_method', models.CharField(choices=[('CASH', 'Nakit'), ('CREDIT_CARD', 'Kredi Kartı'), ('BANK_TRANSFER', 'Havale/EFT'), ('CHECK', 'Çek'), ('OTHER', 'Diğer')], default='CASH', max_length=20, verbose_name='Ödeme Yöntemi')),
                ('vendor', models.CharField(blank=True, max_length=200, verbose_name='Tedarikçi/Firma')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expense_receipts/', verbose_name='Fiş/Fatura Görseli')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Tekrarlayan Gider')),
                ('recurring_type', models.CharField(choices=[('NONE', 'Tek Seferlik'), ('MONTHLY', 'Aylık'), ('QUARTERLY', 'Üç Aylık'), ('YEARLY', 'Yıllık')], default='NONE', max_length=20, verbose_name='Tekrar Tipi')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Sonraki Vade Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('related_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockmovement', verbose_name='İlişkili Alım')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.expensecategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Gider',
                'verbose_name_plural': 'Giderler',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bütçe Tutarı')),
                ('period_start', models.DateField(verbose_name='Dönem Başlangıcı')),
                ('period_end', models.DateField(verbose_name='Dönem Bitişi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expensecategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Gider Bütçesi',
                'verbose_name_plural': 'Gider Bütçeleri',
                'unique_together': {('category', 'period_start', 'period_end')},
            },
        ),
    ]
