# Generated by Django 5.2.5 on 2025-08-17 03:11

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0003_add_product_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kural Adı')),
                ('category', models.CharField(choices=[('SERVICE', 'Servis İşlemleri'), ('ATTENDANCE', 'Mesai/Devam'), ('QUALITY', 'Kalite'), ('CUSTOMER', 'Müşteri Memnuniyeti'), ('TEAM', 'Takım Çalışması'), ('PENALTY', 'Ceza')], max_length=20)),
                ('action', models.CharField(choices=[('SERVICE_ACCEPTED', 'Servis Kabul Edildi'), ('SERVICE_DIAGNOSED', 'Arıza Tespiti Yapıldı'), ('SERVICE_REPAIRED', 'Onarım Tamamlandı'), ('SERVICE_DELIVERED', 'Müşteriye Teslim Edildi'), ('SERVICE_FAST_COMPLETION', 'Hızlı Tamamlama (<24 saat)'), ('SERVICE_DELAYED', 'Gecikmiş Servis'), ('ON_TIME', 'Zamanında Geldi'), ('LATE_ARRIVAL', 'Geç Kaldı'), ('EARLY_LEAVE', 'Erken Çıktı'), ('ABSENT', 'Gelmedi'), ('OVERTIME', 'Fazla Mesai'), ('NO_REWORK', 'İade/Tekrar İşlem Yok'), ('REWORK_REQUIRED', 'İade/Tekrar İşlem Gerekti'), ('CUSTOMER_COMPLAINT', 'Müşteri Şikayeti'), ('CUSTOMER_SATISFACTION', 'Müşteri Memnuniyeti'), ('MONTHLY_TARGET_ACHIEVED', 'Aylık Hedef Başarıldı'), ('TEAM_SUPPORT', 'Takım Arkadaşına Destek'), ('TRAINING_COMPLETED', 'Eğitim Tamamlandı')], max_length=50, unique=True)),
                ('points', models.DecimalField(decimal_places=2, help_text='Pozitif puan için +, negatif için - değer girin', max_digits=8, verbose_name='Puan')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_apply', models.BooleanField(default=False, help_text='Bu kural sistem tarafından otomatik uygulanacak mı?', verbose_name='Otomatik Uygula')),
            ],
            options={
                'verbose_name': 'Puanlama Kuralı',
                'verbose_name_plural': 'Puanlama Kuralları',
                'ordering': ['category', 'points'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mesai Adı')),
                ('start_time', models.TimeField(default=datetime.time(8, 0), verbose_name='Başlangıç')),
                ('end_time', models.TimeField(default=datetime.time(18, 0), verbose_name='Bitiş')),
                ('saturday_start', models.TimeField(default=datetime.time(8, 0), verbose_name='Cumartesi Başlangıç')),
                ('saturday_end', models.TimeField(default=datetime.time(13, 0), verbose_name='Cumartesi Bitiş')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mesai Saatleri',
                'verbose_name_plural': 'Mesai Saatleri',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='Giriş Saati')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Çıkış Saati')),
                ('status', models.CharField(choices=[('ON_TIME', 'Zamanında'), ('LATE', 'Geç Kaldı'), ('EARLY', 'Erken Çıktı'), ('ABSENT', 'Gelmedi'), ('HOLIDAY', 'İzinli')], default='ON_TIME', max_length=20)),
                ('late_minutes', models.IntegerField(default=0, verbose_name='Geç Kalınan Dakika')),
                ('early_leave_minutes', models.IntegerField(default=0, verbose_name='Erken Çıkılan Dakika')),
                ('total_work_minutes', models.IntegerField(default=0, verbose_name='Toplam Çalışma (dk)')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mesai Kaydı',
                'verbose_name_plural': 'Mesai Kayıtları',
                'ordering': ['-date'],
                'unique_together': {('technician', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.attendancerecord')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_point_transactions', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.pointrule')),
                ('service_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.servicerecord')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Puan İşlemi',
                'verbose_name_plural': 'Puan İşlemleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(verbose_name='İşe Başlama Tarihi')),
                ('monthly_target', models.IntegerField(default=50, verbose_name='Aylık Servis Hedefi')),
                ('is_active', models.BooleanField(default=True)),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_month_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
                ('work_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance.workschedule')),
            ],
            options={
                'verbose_name': 'Teknisyen Profili',
                'verbose_name_plural': 'Teknisyen Profilleri',
            },
        ),
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('total_services', models.IntegerField(default=0)),
                ('completed_services', models.IntegerField(default=0)),
                ('avg_completion_time', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ort. Tamamlama Süresi (saat)')),
                ('total_work_days', models.IntegerField(default=0)),
                ('on_time_days', models.IntegerField(default=0)),
                ('late_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('total_late_minutes', models.IntegerField(default=0)),
                ('service_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attendance_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quality_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('penalty_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Aylık Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performans Raporu',
                'verbose_name_plural': 'Performans Raporları',
                'ordering': ['-year', '-month', '-total_points'],
                'unique_together': {('technician', 'year', 'month')},
            },
        ),
    ]
