# Generated by Django 5.1.3 on 2025-07-02 01:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Servis ID')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Kabul Edildi'), ('DIAGNOSIS', 'Arıza Tespiti Yapılıyor'), ('WAITING_FOR_PART', 'Parça Bekleniyor'), ('IN_REPAIR', 'Onarımda'), ('REPAIRED', 'Onarım Tamamlandı'), ('DELIVERED', 'Müşteriye Teslim Edildi'), ('CANCELLED', 'İptal Edildi')], default='ACCEPTED', max_length=20, verbose_name='Servis Durumu')),
                ('machine_brand', models.CharField(max_length=100, verbose_name='Makine Markası')),
                ('machine_model', models.CharField(max_length=100, verbose_name='Makine Modeli')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Seri Numarası')),
                ('customer_complaint', models.TextField(verbose_name='Müşteri Şikayeti')),
                ('technician_notes', models.TextField(blank=True, verbose_name='Teknisyen Notları / Yapılan İşlemler')),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='service_barcodes/', verbose_name='Servis Barkod Resmi')),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='İşçilik Ücreti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kabul Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atanan Personel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Servis Kaydı',
                'verbose_name_plural': 'Servis Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Kullanılan Adet')),
                ('price_at_time_of_use', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kullanım Anındaki Fiyat')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Kullanılan Parça')),
                ('service_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='service.servicerecord', verbose_name='Servis Kaydı')),
            ],
            options={
                'verbose_name': 'Kullanılan Servis Parçası',
                'verbose_name_plural': 'Kullanılan Servis Parçaları',
            },
        ),
    ]
