# Generated by Django 5.1.3 on 2025-07-10 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_shelf_product_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Raf Kodu/Numarası')),
            ],
            options={
                'verbose_name': 'Raf',
                'verbose_name_plural': 'Raflar',
                'ordering': ['warehouse', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Depo Adı')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Konum/Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Depo',
                'verbose_name_plural': 'Depolar',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='warehouse',
        ),
        migrations.AlterField(
            model_name='product',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.shelf', verbose_name='Raf'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='inventory.warehouse', verbose_name='Ait Olduğu Depo'),
        ),
        migrations.AlterUniqueTogether(
            name='shelf',
            unique_together={('warehouse', 'code')},
        ),
    ]
