# Generated by Django 5.2.4 on 2025-07-28 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0004_remove_sale_credit_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kredi Limiti (₺)')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Güncel Bakiye (₺)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloke')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Cari Hesap',
                'verbose_name_plural': 'Cari Hesaplar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('SALE', 'Satış (Borç)'), ('PAYMENT', 'Ödeme (Alacak)'), ('ADJUSTMENT', 'Düzeltme'), ('INITIAL', 'Başlangıç Bakiyesi')], max_length=20, verbose_name='İşlem Tipi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (₺)')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='Referans No')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vade Tarihi')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ödendi')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='current_accounts.creditaccount', verbose_name='Cari Hesap')),
                ('related_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale', verbose_name='İlişkili Satış')),
            ],
            options={
                'verbose_name': 'Cari Hareket',
                'verbose_name_plural': 'Cari Hareketler',
                'ordering': ['-created_at'],
            },
        ),
    ]
