# Generated by Django 5.1.3 on 2025-07-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Bireysel'), ('CORPORATE', 'Kurumsal')], default='INDIVIDUAL', max_length=10, verbose_name='Müşteri Tipi')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Adı')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Soyadı')),
                ('tckn', models.CharField(blank=True, help_text='Bireysel müşteriler için 11 haneli T.C. Kimlik Numarası.', max_length=11, verbose_name='T.C. Kimlik Numarası')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Firma Ticari Ünvanı')),
                ('tax_office', models.CharField(blank=True, max_length=100, verbose_name='Vergi Dairesi')),
                ('tax_number', models.CharField(blank=True, help_text='Kurumsal müşteriler için 10 haneli Vergi Numarası.', max_length=10, verbose_name='Vergi Kimlik Numarası (VKN)')),
                ('contact_person', models.CharField(blank=True, max_length=150, verbose_name='Yetkili Kişi (Kurumsal için)')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Telefon Numarası')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('notes', models.TextField(blank=True, verbose_name='Müşteri Hakkında Notlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
    ]
