# Generated by Django 5.2.4 on 2025-07-21 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0001_initial'),
        ('service', '0002_servicerecord_kdv_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_credit_sale', models.BooleanField(default=False, verbose_name='Veresiye Satış')),
                ('credit_due_date', models.DateField(blank=True, null=True, verbose_name='Vade Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kredi Limiti')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mevcut Bakiye')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Müşteri Cari Hesabı',
                'verbose_name_plural': 'Müşteri Cari Hesapları',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('SALE', 'Satış (Borç)'), ('PAYMENT', 'Ödeme (Alacak)'), ('ADJUSTMENT', 'Düzeltme'), ('SERVICE', 'Servis (Borç)')], max_length=20, verbose_name='İşlem Tipi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vade Tarihi')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ödendi mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.creditaccount', verbose_name='Cari Hesap')),
                ('related_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale', verbose_name='İlişkili Satış')),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.servicerecord', verbose_name='İlişkili Servis')),
            ],
            options={
                'verbose_name': 'Veresiye İşlemi',
                'verbose_name_plural': 'Veresiye İşlemleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
