# Generated by Django 5.2.4 on 2025-07-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_sale_creditaccount_credittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='default_payment_days',
            field=models.PositiveIntegerField(default=30, help_text='Yeni borçlar için varsayılan vade süresi', verbose_name='Varsayılan Vade Süresi (Gün)'),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='notes',
            field=models.TextField(blank=True, help_text='Bu müşterinin cari hesabı hakkında özel notlar', verbose_name='Cari Hesap Notları'),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='payment_terms',
            field=models.TextField(blank=True, help_text='Özel ödeme koşulları ve anlaşmalar', verbose_name='Ödeme Koşulları'),
        ),
    ]
