# Generated by Django 5.1.3 on 2025-06-14 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'Giriş Yaptı'), ('LOGOUT', 'Çıkış Yaptı'), ('CREATE', 'Oluşturma'), ('UPDATE', 'Güncelleme'), ('DELETE', 'Silme'), ('VIEW', 'Görüntüleme')], max_length=10, verbose_name='İşlem Tipi')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman Damgası')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Aktivite Kaydı',
                'verbose_name_plural': 'Aktivite Kayıtları',
                'ordering': ['-timestamp'],
            },
        ),
    ]
