# Generated by Django 5.1.3 on 2025-07-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='kdv_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=20.0, max_digits=5, verbose_name='KDV Oranı (%)'),
        ),
    ]
