# Generated by Django 5.1.3 on 2025-07-02 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Marka Adı')),
                ('slug', models.SlugField(blank=True, help_text='Bu alan otomatik olarak doldurulacaktır.', max_length=170, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Alım'), ('SALE', 'Satış'), ('RETURN_CUSTOMER', 'Müşteri İadesi'), ('RETURN_SUPPLIER', 'Tedarikçiye İade'), ('ADJUSTMENT_IN', 'Stok Sayım Fazlası'), ('ADJUSTMENT_OUT', 'Stok Sayım Eksiği (Fire)'), ('INITIAL_STOCK', 'Başlangıç Stoku')], max_length=20, verbose_name='Hareket Tipi')),
                ('quantity', models.IntegerField(verbose_name='Miktar')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Zamanı')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar/Açıklama')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tedarikçi Adı')),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True, verbose_name='Yetkili Kişi')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta Adresi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Tedarikçi',
                'verbose_name_plural': 'Tedarikçiler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, help_text='Bu alan otomatik olarak doldurulacaktır.', max_length=220, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.category', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ürün Kodu (SKU)')),
                ('barcode_data', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barkod Verisi')),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/', verbose_name='Barkod Resmi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Ürün Resmi')),
                ('model_compatibility', models.CharField(blank=True, max_length=255, null=True, verbose_name='Model Uyumluluğu')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Alış Fiyatı')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı')),
                ('quantity', models.IntegerField(default=0, verbose_name='Mevcut Stok Miktarı')),
                ('min_stock_level', models.PositiveIntegerField(default=5, verbose_name='Minimum Stok Seviyesi')),
                ('unit', models.CharField(choices=[('adet', 'Adet'), ('takim', 'Takım'), ('metre', 'Metre'), ('kg', 'Kilogram'), ('litre', 'Litre')], default='adet', max_length=10, verbose_name='Birim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.brand', verbose_name='Marka')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['name'],
            },
        ),
    ]
