# Generated by Django 5.1.3 on 2025-07-02 01:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Vergi Adı')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Örn: 20.00', max_digits=5, verbose_name='Oran (%)')),
            ],
            options={
                'verbose_name': 'Vergi Oranı',
                'verbose_name_plural': 'Vergi Oranları',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Satış Tarihi')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi')], default='DRAFT', max_length=10, verbose_name='Durum')),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Nakit'), ('CREDIT_CARD', 'Kredi Kartı'), ('BANK_TRANSFER', 'Havale/EFT')], max_length=20, null=True, verbose_name='Ödeme Yöntemi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ara Toplam')),
                ('vat_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='KDV Toplamı')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Genel Toplam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Müşteri')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Satışı Yapan Personel')),
            ],
            options={
                'verbose_name': 'Satış',
                'verbose_name_plural': 'Satışlar',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miktar')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat (Satış Anı)')),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Vergi Oranı (Satış Anı)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Ürün')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Satış')),
            ],
        ),
    ]
