# Generated by Django 5.2.4 on 2025-07-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Nakit'), ('CREDIT_CARD', 'Kredi Kartı'), ('BANK_TRANSFER', 'Havale/EFT'), ('CREDIT', 'Veresiye')], max_length=20, null=True, verbose_name='Ödeme Yöntemi'),
        ),
    ]
