# Generated by Django 5.2.4 on 2025-07-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_credit_due_date_sale_is_credit_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='credit_due_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_credit_sale',
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Nakit'), ('CREDIT_CARD', 'Kredi Kartı'), ('BANK_TRANSFER', 'Havale/EFT')], max_length=20, null=True, verbose_name='Ödeme Yöntemi'),
        ),
    ]
